### ISSUE TITLE
multiple responsive props return incomplete media query

### ISSUE THREAD

**Issue by queckezz** [jxnblk/axs#8]
Given the following `props` on any `withAxs`-wrapped component:

```js
{
  width: [1, 2/3]
  pr: [0, 1]
}
```

This only generates a `cxs` media query for the last responsive props given:
```css
@media screen and (min-width:40em) {
  .cxs-12406165 {
    padding-right:8px
   /** -> missing `width` here */
  }
}
```

I just throw this out here in case you run into it too. I'll eventually send a PR.
